import Head from 'next/head';
import { useState } from 'react';
import styles from '@components:./components/styles/Home.module.scss';
import clsx from 'clsx';

export default function Home() {
  const [showCompetences, setShowCompetences] = useState(false);

  const techs = [
    {name: "JS", part: ",", color: "orange"},
    {name: "TS", part: ",", color: "{30}7C6"},
    {name: "React", part: "&", color: "#61DAFB"},
    {name: "Next", color: "grey"}
  ]

  const leftSideSkills = [
    {name: "JS:", value: 90},
    {name: "TS:", value: 90},
    {name: "React:", value: 90},
    {name: "Next:", value: 80},
    {name: "AWS Amplify:", value: 30},
    {name: "GraphQL:", value: 30},
    {name: "Node:", value: 40},
    {name: "Express:", value: 40},
  ]

  const rightSideSkills = [
    {name: "Jest:", value: 60},
    {name: "RTL:", value: 60},
    {name: "Redux:", value: 50},
    {name: "HTML:", value: 90},
    {name: "CSS:", value: 90},
    {name: "Sass:", value: 70},
    {name: "Git:", value: 60}
  ]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght{40};500{70}&display=swap" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home_container}>
        <header className={styles.home_header_container}>
            <h1>Developper Fron-end React & Next TypeScipt</h1>
            <p>Hello, I am Doukhaev Israil. A passionate developer, i hope you will like my portfolio.</p>
          </header>
        <main className={styles.home_main_container}>
          <div className={styles.home_left_side_container}>
            <p className={styles.home_left_side_p}>
              Doukhaev Israil is a passionate and self-taught {techs.map((tech, index) => <><span key={index} style={{color: tech.color}}> {tech.name}</span> {tech.part}</>)}
              developer, having started programming at the age of 16. He has a varied professional experience, 
              working on various projects such as The Gems Hunter, Waynah Architecture Agency and Fason, 
              where he acquired skills in React, Next, TypeScript, etc. <br />
              Israil stands out for its excellent understanding of key concepts and its rigorous application 
              of good development practices. In addition to his technical skills, Israil is proactive and actively 
              participates in team meetings and training workshops to constantly improve his skills. 
              A regular participant in online conferences and trainings, 
              Israil is a committed developer and always up to date with the latest trends in React development.
            </p>
          </div>
          <div className={styles.home_right_side_container}>
            <img className={clsx(
              styles.home_my_image, 
              showCompetences ? `${styles.home_change_opacity} ${styles.home_image_zoom}` : null)} 
              src="/ISRAIL.jpg" alt='image of Doukhaev Israil' 
              onMouseOver={() => setShowCompetences(true)} onMouseOut={() => setShowCompetences(false)} 
            />
            <h4 className={clsx(styles.home_skills_title, showCompetences ? styles.home_competences_show : null)} onMouseOver={() => setShowCompetences(true)}>Skills</h4>
            <div className={clsx(styles.home_competences, showCompetences ? styles.home_competences_show : null)} onMouseOver={() => setShowCompetences(true)}>
              <div className={styles.home_left_side_skills}>
                {
                  leftSideSkills.map((skill, index) => {
                    return (
                      <div key={index}>
                        {skill.name} <br/><meter min={0} max={100} low={30} high={70} optimum={80} value={skill.value}/>
                      </div>
                    )
                  })
                }
              </div>
              <div>
                {
                  rightSideSkills.map((skill, index) => {
                    return (
                      <div key={index}>
                        {skill.name} <br/><meter min={0} max={100} low={30} high={70} optimum={80} value={skill.value}/>
                      </div>
                    )
                  })
                }
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  )
}